# Change these first
owner: onuralpszr # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Fedora Project
    url: https://getfedora.org/
  - name: RPMFusion
    url: https://rpmfusion.org/
  - name: Start Fedora Project 
    url: https://start.fedoraproject.org/
  - name: Pagure.io
    url: https://pagure.io/
  - name: openSUSE Bar
    url: https://meet.opensuse.org/
  - name: element.io
    url: https://app.element.io/
  - name: CentOS Koji
    url: https://koji.mbox.centos.org/koji/
  - name: Fedora Koji
    url: https://koji.fedoraproject.org/koji/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.onuralpsezer.com
  # baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Onuralp Uptime List 
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  status-website:
    theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
